# Generated by Django 2.2.6 on 2019-11-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs',
            name='user_country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bbs',
            name='user_nick',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
