# Generated by Django 2.2.6 on 2019-11-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
