# Generated by Django 2.2.6 on 2019-11-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_visit_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yyyy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yyyy', models.CharField(max_length=100)),
            ],
        ),
    ]
