# Generated by Django 2.2.6 on 2019-11-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country_group',
            options={'ordering': ['-country_total']},
        ),
    ]
